spring.application.name=demo

# ======================================
# SERVIDOR
# ======================================
server.port=8080

# ======================================
# MYSQL
# ======================================
spring.datasource.url=jdbc:mysql://localhost:3306/librocontable?useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ======================================
# JPA
# ======================================

# Valida que las tablas y columnas existan.
# Si encuentra diferencias, la aplicación no iniciará.
spring.jpa.hibernate.ddl-auto=validate

# Muestra las consultas SQL generadas por Hibernate.
spring.jpa.show-sql=true

# Formatea las consultas SQL para que sean legibles.
spring.jpa.properties.hibernate.format_sql=true

# Dialecto de MySQL.
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ======================================
# HIKARI
# ======================================
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

# ======================================
# LOGGING
# ======================================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE


###############################################################
# OPCIONES DE DDL (Descomentar únicamente cuando sea necesario)
###############################################################

# Crea las tablas nuevamente en cada inicio (ELIMINA TODA LA DATA)
# spring.jpa.hibernate.ddl-auto=create

# Actualiza automáticamente las tablas según las entidades.
# Úsalo solo en desarrollo para agregar nuevas columnas o tablas.
# spring.jpa.hibernate.ddl-auto=update

# Crea las tablas al iniciar y las elimina al detener la aplicación.
# spring.jpa.hibernate.ddl-auto=create-drop

# No realiza ninguna acción sobre el esquema.
# spring.jpa.hibernate.ddl-auto=none